config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Read all tasks
  get 'tasks', to: 'tasks#index', as: :tasks

  # Create one task (2 requests)
  # 1. get empty form
  # 2. Request to post the params
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'
  # Read one task
  get 'tasks/:id', to: 'tasks#show', as: :task
  # Update one task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  # Delete one task
  delete 'tasks/:id', to: 'tasks#destroy', as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task do |t| %>
  <%= t.label :title, "Enter a title" %>
  <%= t.text_field :title %>
  <%= t.label :details, "Enter a details" %>
  <%= t.text_field :details %>
  <%= t.check_box :completed  %>
  <span>Done</span>
  <%= t.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form" %>

<%= link_to "Go back to tasks", tasks_path %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>

<p>Welcome to the page that will display all the tasks</p>

<%= link_to "Add a new task", new_task_path %>

<ul>
<% @tasks.each do |task| %>
<li>
<%= link_to task.title, task_path(task) %>
<%= link_to "Edit", edit_task_path(task) %>
<%= link_to "Delete", delete_task_path(task), method: :delete, data: {confirm: "Are you sure?"} %>
</li>
<% end %>
</ul>

app/views/tasks/new.html.erb
<%= render "form" %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<%= link_to "Go back to tasks", tasks_path %>